In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import os
captions_file = '/content/drive/MyDrive/ROCO/data/train/radiology/captions.txt'
images_path = '/content/drive/MyDrive/ROCO/data/train/radiology/images'

data = []
with open(captions_file, 'r') as f:
    for line in f:
        line = line.strip()
        if not line or '\t' not in line:
            print(f"Skipping line: {line}")
            continue
        try:
            image_id, caption = line.split('\t')
            data.append([image_id, caption, images_path])
        except ValueError:
            print(f"Error processing line: {line}")
df = pd.DataFrame(data, columns=['Image ID', 'Image Caption', 'Image Path'])
print(df.head(5))

Skipping line: ROCO_42292
     Image ID                                      Image Caption  \
0  ROCO_00002   Computed tomography scan in axial view showin...
1  ROCO_00003   Bacterial contamination occurred after comple...
2  ROCO_00004   The patient had residual paralysis of the han...
3  ROCO_00005      Panoramic radiograph after immediate loading.
4  ROCO_00007   Plain abdomen x-ray: Multiple air levels at t...

                                          Image Path
0  /content/drive/MyDrive/ROCO/data/train/radiolo...
1  /content/drive/MyDrive/ROCO/data/train/radiolo...
2  /content/drive/MyDrive/ROCO/data/train/radiolo...
3  /content/drive/MyDrive/ROCO/data/train/radiolo...
4  /content/drive/MyDrive/ROCO/data/train/radiolo...

In [ ]:
def classify_caption(caption):
    abnormal_keywords = [
        'tumor', 'cancer', 'fracture', 'lesion', 'abnormal', 'pathology', 'disease', 'infection', 'swelling', 'blood', 'bleeding', 'mass', 'clot', 'nodules', 'metastasis', 'sarcoma', 'stroke', 'pneumonia', 'hemorrhage', 'infarction', 'diabetes', 'cyst', 'aneurysm', 'calcification', 'ischemia', 'tuberculosis', 'fibrosis', 'sclerosis', 'laceration', 'dislocation', 'nodular', 'congestion', 'edema', 'pneumothorax', 'collapse', 'deformity',
        'scarring', 'stent', 'abscess', 'bronchitis', 'pneumonitis', 'retinopathy', 'osteopenia', 'osteoporosis', 'cardiomegaly', 'calcified', 'pericardial', 'hepatomegaly', 'splenomegaly', 'lymphadenopathy', 'nephropathy', 'colitis', 'gastropathy', 'sepsis', 'chronic', 'necrosis', 'myocardial', 'pulmonary embolism', 'hyperplasia', 'atrophy', 'osteomyelitis', 'autoimmune', 'malignancy', 'neoplasm', 'hemangioma', 'pleural effusion', 'sarcoidosis', 'granuloma',
        'peritonitis', 'hypertension', 'hemodialysis', 'fibrotic', 'lymphoma', 'meningioma', 'diabetic retinopathy', 'cholecystitis', 'pleuritis', 'glaucoma', 'subdural hematoma', 'subarachnoid hemorrhage', 'pneumonectomy', 'retinal detachment', 'myelopathy', 'bronchiectasis', 'lymphocytic', 'reflux', 'pericarditis', 'gallstones', 'splenic infarction', 'biliary obstruction', 'aplastic anemia', 'acute', 'cholecystectomy', 'lymphopenia', 'hemophilia', 'sickle cell', 'asthma',
        'allergy', 'bronchospasm', 'corticosteroids', 'antibiotics', 'hemoptysis', 'peptic ulcer', 'herpes', 'hiv', 'aids', 'candidiasis', 'hyperthyroidism', 'hypothyroidism', 'osteosarcoma', 'epilepsy', 'seizure', 'pneumonitis', 'cardiomyopathy', 'metastatic', 'adenocarcinoma', 'radiation', 'chemotherapy', 'malaria', 'chronic fatigue syndrome', 'bipolar disorder', 'depression', 'schizophrenia', 'anemia', 'hepatitis', 'cirrhosis', 'gout', 'eczema', 'psoriasis', 'lupus', 'pseudomonas',
        'legionella', 'septicemia', 'hyperventilation', 'tachycardia', 'bradycardia', 'dysrhythmia', 'carcinoma', 'hemochromatosis', 'diabetic ketoacidosis', 'hydrocephalus', 'cystic fibrosis', 'multiple sclerosis', 'polyneuropathy', 'encephalopathy', 'autoimmune disease', 'gastroparesis', 'endometriosis', 'colorectal cancer', 'irritable bowel syndrome', 'amyloidosis', 'psoriatic arthritis', 'interstitial lung disease', 'parkinson\'s', 'meningitis', 'encephalitis', 'pneumoniae', 'tracheitis',
        'pleural effusion', 'pericardial effusion', 'mesothelioma', 'peripheral neuropathy', 'hypovolemia', 'hyperkalemia', 'hypokalemia', 'hypernatremia', 'hyponatremia', 'hemorrhagic shock', 'cholestasis', 'malabsorption', 'dehydration', 'intussusception', 'intubation', 'hypoxia', 'hypocapnia', 'severe headache', 'nausea', 'vomiting', 'hemodynamic instability', 'cerebrovascular accident', 'hysterectomy', 'ovarian cysts', 'pancreatitis', 'deep vein thrombosis', 'pulmonary fibrosis', 'stent graft',
        'cardiac arrest', 'chronic obstructive pulmonary disease', 'diabetic retinopathy', 'gastropathy', 'blood clot', 'hemophilia', 'endocarditis', 'cirrhosis', 'rheumatoid arthritis', 'hepatomegaly', 'splenomegaly', 'abdominal pain', 'melena', 'epigastric pain', 'bronchiolitis', 'hypoalbuminemia', 'hydropneumothorax', 'gastrectomy', 'vulvovaginal candidiasis', 'pleural plaque', 'sick sinus syndrome', 'thrombophlebitis', 'pneumoconiosis', 'emphysema', 'benign prostatic hyperplasia', 'hyperlipidemia', 'gallbladder', 'cystic adenoma', 'neuroblastoma', 'bladder cancer', 'renal failure', 'ascending aortic aneurysm', 'sinusitis', 'menorrhagia', 'gastroesophageal reflux disease', 'adrenal insufficiency', 'fibrosarcoma', 'vesicoureteral reflux', 'lumbosacral strain'
    ]
    for keyword in abnormal_keywords:
        if keyword.lower() in caption.lower():
            return 1
    return 0
df['label'] = df['Image Caption'].apply(classify_caption)

NORMAL --> 0           
ABNORMAL --> 1

In [ ]:
random_sample = df.sample(n=5)
print(random_sample)

         Image ID                                      Image Caption  \
22290  ROCO_27779   Contrast enhanced MRI of the left knee demons...
52007  ROCO_64966   After 65 days from the afatinib 40 mg adminis...
33090  ROCO_41334   Demonstrates bony infill with the nasopharyng...
3139   ROCO_03907   Angiography, sagittal view, showing the absen...
18850  ROCO_23514   The CT scan obtained on the fourteenth hospit...

                                              Image Path  label
22290  /content/drive/MyDrive/ROCO/data/train/radiolo...      1
52007  /content/drive/MyDrive/ROCO/data/train/radiolo...      1
33090  /content/drive/MyDrive/ROCO/data/train/radiolo...      0
3139   /content/drive/MyDrive/ROCO/data/train/radiolo...      0
18850  /content/drive/MyDrive/ROCO/data/train/radiolo...      0

In [ ]:
train_texts = df['Image Caption'][:8000]
test_texts = df['Image Caption'][8000:10000]

train_labels = df['label'][:8000]
test_labels = df['label'][8000:10000]

In [ ]:
train_texts.head()

0     Computed tomography scan in axial view showin...
1     Bacterial contamination occurred after comple...
2     The patient had residual paralysis of the han...
3        Panoramic radiograph after immediate loading.
4     Plain abdomen x-ray: Multiple air levels at t...
Name: Image Caption, dtype: object

In [ ]:
test_labels.head()

8000    1
8001    1
8002    0
8003    1
8004    0
Name: label, dtype: int64

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(train_texts)

In [ ]:
train_sequences=tokenizer.texts_to_sequences(train_texts)
test_sequences=tokenizer.texts_to_sequences(test_texts)

In [ ]:
train_sequences

[[21, 18, 14, 5, 25, 24, 7, 1278, 2, 1, 8, 262, 123],
 [4527,
  6341,
  2200,
  26,
  1629,
  2,
  350,
  265,
  201,
  5,
  1,
  497,
  110,
  2022,
  6,
  4,
  4528,
  263,
  83,
  617,
  295],
 [1,
  33,
  321,
  430,
  4529,
  2,
  1,
  726,
  26,
  6342,
  231,
  27,
  4530,
  12,
  4531,
  1,
  1630,
  6,
  1032,
  12,
  1,
  967,
  1443,
  76,
  27,
  6343,
  45,
  3657,
  4,
  338,
  36,
  1,
  64,
  6344,
  98,
  1,
  218,
  3,
  274,
  2684,
  1,
  1744,
  16,
  1,
  181,
  1079,
  2,
  1,
  338,
  242,
  39,
  545],
 [151, 23, 26, 911, 2685],
 [178,
  58,
  30,
  31,
  87,
  137,
  765,
  17,
  1,
  328,
  58,
  37,
  63,
  968,
  596,
  3,
  63,
  137,
  766,
  1,
  669],
 [4,
  65,
  39,
  38,
  878,
  6,
  2686,
  6345,
  25,
  570,
  13,
  347,
  4,
  2403,
  2404,
  32,
  259,
  12,
  1,
  322,
  440,
  227,
  1,
  554,
  3102,
  37,
  6,
  466,
  19,
  670,
  1171,
  6,
  554,
  2687,
  570,
  822,
  15,
  149,
  269,
  5,
  1,
  8,
  6346,
  36,
  1223,
  2023,
  503],
 [7, 1, 2688, 78, 5, 1, 6347, 64],
 [90, 2689, 201, 350, 265, 390, 1172, 6, 262, 1444],
 [144, 3658, 2201, 5, 1, 85, 161, 2, 1, 2690, 2024, 50, 4532],
 [29,
  597,
  2,
  34,
  13,
  104,
  3103,
  6348,
  2,
  197,
  187,
  42,
  28,
  683,
  5,
  423,
  6349,
  6350,
  2405,
  30,
  2405,
  2691],
 [878,
  6,
  3659,
  3,
  2202,
  2,
  9,
  66,
  1542,
  3,
  3660,
  2,
  1,
  684,
  22,
  1,
  364,
  351,
  6,
  467,
  2,
  1,
  8,
  198,
  1851,
  1,
  941,
  2,
  1,
  4533,
  211,
  2,
  6351,
  5,
  6352,
  2,
  1371,
  467,
  4,
  1744,
  2,
  1,
  6353,
  107,
  242,
  685,
  266,
  3661,
  68,
  76,
  260,
  969,
  5,
  6354],
 [25,
  69,
  4534,
  195,
  13,
  16,
  424,
  2,
  99,
  4535,
  2203,
  3662,
  3,
  270,
  370,
  1745,
  2,
  1279,
  17,
  1,
  362,
  2,
  300,
  2,
  1631,
  5,
  1852,
  2,
  204,
  102,
  10,
  598,
  115,
  12,
  1,
  995,
  99,
  4535,
  131,
  571,
  2,
  1631,
  264,
  112,
  59,
  17,
  699,
  441,
  40,
  37],
 [848, 277, 5, 1173],
 [105, 185, 44, 970, 6355, 3, 4532, 412],
 [431, 1746, 7, 99, 6356, 3, 4, 74, 3663],
 [155,
  127,
  105,
  125,
  3,
  912,
  68,
  4,
  1632,
  5,
  1,
  179,
  3664,
  4,
  487,
  4,
  1632,
  5,
  1,
  179,
  3664],
 [9,
  228,
  1747,
  5,
  6357,
  356,
  6358,
  531,
  700,
  6359,
  6360,
  229,
  4,
  1543,
  1853,
  104,
  15,
  132,
  2204,
  36,
  1,
  64,
  335],
 [1033, 849, 34],
 [1080],
 [370, 4536, 2, 1, 81, 532],
 [106, 2025, 384, 1633, 4537, 6361],
 [48, 51, 69, 53, 13, 7, 2692, 4538, 2, 1, 599],
 [90, 201, 6362, 82, 53, 28, 54, 13, 7, 1, 260, 32, 42, 232, 65],
 [47, 11, 14, 7, 238, 2205],
 [25,
  28,
  54,
  21,
  18,
  13,
  2,
  1,
  58,
  65,
  109,
  26,
  2206,
  2693,
  201,
  7,
  181,
  243,
  2,
  1,
  124],
 [457, 124, 37, 208, 1, 743],
 [912, 13, 2, 3665, 572],
 [249, 107, 30, 31, 244, 130, 371, 36, 222, 533, 110, 16, 671, 141, 96, 744],
 [91, 727, 223, 418, 224],
 [11,
  13,
  2,
  1,
  81,
  16,
  137,
  5,
  1,
  169,
  534,
  10,
  3,
  137,
  28,
  88,
  5,
  1,
  147,
  296,
  301,
  172],
 [3104, 2694, 26, 6363, 442, 5, 29, 3105, 12, 488, 1, 32],
 [91, 21, 18, 14],
 [600,
  39,
  38,
  233,
  6,
  297,
  74,
  329,
  25,
  850,
  121,
  1174,
  1280,
  195,
  13,
  2,
  1,
  107],
 [30, 31, 727, 2, 1544, 6364],
 [942,
  13,
  2,
  1,
  4539,
  107,
  44,
  143,
  432,
  1,
  1372,
  15,
  218,
  996,
  89,
  1,
  41,
  4540,
  3,
  1373,
  745,
  4541,
  1445,
  104,
  584,
  13,
  2207,
  15,
  2695,
  913,
  4542,
  3657,
  1124,
  22,
  1,
  1446,
  143,
  432,
  15,
  443,
  36,
  138,
  12,
  479,
  1175,
  1,
  4543,
  265,
  15,
  149,
  212,
  3,
  264,
  112,
  2696,
  45,
  405,
  6365,
  1,
  41,
  3,
  55,
  143,
  943,
  75,
  2,
  997,
  451],
 [633, 7, 4, 97, 157, 3106, 686, 701, 144, 1545, 3107],
 [21,
  18,
  14,
  244,
  22,
  2406,
  944,
  2208,
  234,
  498,
  266,
  201,
  1634,
  14,
  108,
  4,
  19,
  5,
  1,
  61,
  60,
  2,
  1,
  8,
  71,
  87,
  225,
  226,
  468,
  5,
  1,
  433,
  3,
  145,
  187,
  10,
  352,
  2697,
  672,
  187,
  323,
  1,
  1748],
 [43,
  28,
  20,
  11,
  13,
  7,
  1,
  144,
  2407,
  412,
  40,
  10,
  406,
  1854,
  36,
  1,
  170,
  204,
  3,
  1,
  8,
  66,
  60,
  117,
  32],
 [2026,
  1855,
  5,
  1,
  364,
  25,
  11,
  14,
  16,
  4,
  3108,
  10,
  100,
  1,
  452,
  6,
  288,
  618,
  879,
  172],
 [252,
  1447,
  24,
  23,
  7,
  851,
  2,
  252,
  601,
  6,
  4544,
  1546,
  6,
  3109,
  12,
  1374,
  3,
  1448],
 [998, 702, 195, 13, 7, 1, 74, 3, 1, 218, 6366, 746],
 [391, 137, 2408, 1, 669, 17, 47, 30, 31, 602],
 [1125,
  278,
  1176,
  266,
  4545,
  7,
  1,
  147,
  296,
  2027,
  673,
  2,
  1,
  1449,
  971,
  2409,
  767,
  12,
  1,
  3110,
  1,
  444,
  2,
  1,
  1281,
  15,
  1081,
  767,
  1,
  9,
  188,
  67,
  17,
  104,
  348,
  29,
  4546,
  999,
  27,
  1000,
  3666],
 [1282, 6367, 515, 1450, 458, 914, 1283],
 [2698,
  2,
  8,
  2028,
  72,
  353,
  175,
  2410,
  654,
  9,
  213,
  141,
  72,
  1,
  362,
  2,
  915,
  15,
  97,
  59],
 [11, 156, 7, 4, 19, 17, 88, 2, 1126, 6, 212, 1082, 516],
 [6368,
  71,
  302,
  12,
  2699,
  79,
  972,
  5,
  4,
  1034,
  39,
  38,
  687,
  11,
  14,
  71,
  372,
  16,
  199,
  57,
  62,
  3,
  52,
  137,
  564,
  117,
  124,
  102,
  37,
  351,
  6,
  517,
  535,
  445,
  3,
  2700,
  2701,
  4547,
  124,
  22,
  1,
  9,
  40,
  37],
 [24, 2, 973, 603, 74, 2, 1630, 1749, 2209],
 [34, 7, 140, 1375, 208, 1, 136, 70, 123, 518, 22, 6369],
 [326,
  303,
  298,
  619,
  1177,
  275,
  207,
  24,
  167,
  688,
  284,
  27,
  1750,
  852,
  22,
  4548,
  2025,
  231,
  27,
  545,
  573,
  45,
  105,
  125,
  853,
  1751,
  784,
  853,
  1223,
  1856,
  784],
 [158, 24, 2, 71, 353, 21, 18, 6370, 555, 15, 59],
 [3667,
  2,
  365,
  215,
  101,
  4549,
  654,
  3668,
  916,
  36,
  619,
  275,
  207,
  24,
  5,
  242,
  33,
  6,
  365,
  1857,
  304,
  4550,
  26,
  4551],
 [6371,
  2,
  1,
  574,
  6,
  95,
  235,
  245,
  4552,
  1635,
  4553,
  3,
  2210,
  785,
  519,
  1,
  442,
  453,
  768,
  1451,
  127,
  2,
  4,
  3669,
  3670,
  3671,
  2411,
  1376,
  6,
  4,
  2702,
  6372,
  3672,
  4554],
 [1, 249, 24, 23, 2, 1, 9, 198, 108, 115, 1636, 2, 1, 1377, 1547],
 [30, 31, 3111, 7, 270, 28, 1452, 227, 1, 115, 46, 239, 2, 1, 141, 459],
 [4555, 6373, 1127, 16, 140, 131, 728, 1035, 398, 32, 22, 2703],
 [21,
  18,
  25,
  129,
  26,
  315,
  2,
  28,
  689,
  5,
  786,
  348,
  7,
  4,
  52,
  329,
  5,
  1,
  8,
  133,
  72,
  259,
  36,
  1,
  620,
  133,
  534,
  12,
  1,
  147,
  296,
  301,
  2412,
  45,
  363,
  728],
 [91,
  151,
  23,
  26,
  224,
  1,
  6374,
  338,
  27,
  6375,
  12,
  1,
  8,
  604,
  101,
  3,
  2704,
  22,
  1,
  8,
  252,
  974,
  45,
  1453,
  6376,
  1178,
  83,
  3112,
  138,
  425],
 [6377,
  1454,
  701,
  854,
  6378,
  2,
  73,
  499,
  121,
  6379,
  1637,
  3,
  699,
  191,
  1224,
  34,
  82,
  1638,
  413,
  378,
  43],
 [1639,
  151,
  3673,
  36,
  6380,
  7,
  366,
  64,
  424,
  2,
  1,
  9,
  336,
  8,
  2211,
  480,
  3,
  974],
 [20, 278, 16, 4, 19, 22, 1, 9, 66, 433],
 [769,
  3113,
  81,
  292,
  4,
  855,
  39,
  38,
  233,
  6,
  1548,
  2,
  1,
  9,
  41,
  20,
  67,
  1,
  33,
  1640,
  2212,
  130,
  1378,
  12,
  1,
  9,
  20,
  67,
  11,
  244,
  95,
  371,
  26,
  1,
  1629,
  2,
  769,
  390,
  16,
  4,
  97,
  157,
  101,
  2,
  250,
  445,
  5,
  1,
  81,
  6,
  4,
  2029,
  2213,
  98,
  1,
  101,
  2,
  769,
  3,
  1,
  99,
  81,
  76,
  15,
  251,
  6,
  1,
  1083,
  434,
  385,
  2,
  769,
  856],
 [6381, 350, 265, 6, 1858],
 [41,
  55,
  23,
  2,
  1,
  8,
  520,
  2,
  4,
  787,
  39,
  38,
  276,
  33,
  7,
  1,
  1752,
  316,
  2,
  1,
  2705,
  2413,
  197,
  6,
  29,
  3114,
  1225,
  2,
  253,
  95,
  2413,
  1641],
 [11, 96, 6, 621, 28, 6, 29, 10, 104, 352, 311, 297, 123, 518],
 [205,
  30,
  31,
  1284,
  26,
  1,
  11,
  68,
  1,
  460,
  1128,
  3,
  405,
  1642,
  330,
  5,
  1,
  66,
  107],
 [254, 2, 1, 312, 170, 204, 6, 4, 158, 182, 2, 65, 4556],
 [28,
  34,
  96,
  25,
  129,
  7,
  29,
  6382,
  173,
  19,
  5,
  1,
  9,
  171,
  322,
  60,
  880,
  5,
  1,
  729,
  2214,
  12,
  1,
  703,
  123,
  3,
  3674,
  219,
  10],
 [3115,
  1285,
  331,
  2,
  1455,
  2414,
  5,
  4,
  33,
  6,
  730,
  2030,
  332,
  3,
  3675,
  277,
  2,
  1,
  138,
  1455,
  2414,
  4557,
  10,
  200,
  192,
  4,
  41,
  3,
  857,
  55],
 [20,
  30,
  31,
  110,
  573,
  1,
  211,
  2,
  1753,
  259,
  36,
  1,
  9,
  138,
  575,
  72,
  127,
  12,
  147,
  296,
  301],
 [70, 11, 185, 2, 58, 44, 1379, 2415, 3, 634, 2, 179],
 [6383,
  208,
  1,
  1754,
  239,
  2,
  1,
  285,
  115,
  2031,
  118,
  104,
  231,
  3103,
  22,
  1,
  277,
  2,
  6384,
  6385,
  6386],
 [655, 1286, 44, 1, 2032, 277, 2, 1, 3676],
 [238,
  469,
  10,
  635,
  5,
  326,
  303,
  289,
  142,
  4,
  941,
  2,
  1,
  1755,
  2,
  3116,
  35,
  4,
  2706,
  2,
  249],
 [975, 125, 7, 1, 481, 2, 6387, 5, 4, 49, 295, 38, 132, 976, 10],
 [41,
  3677,
  6,
  2707,
  2033,
  280,
  5,
  4,
  2416,
  39,
  38,
  261,
  6,
  6388,
  41,
  3677,
  367,
  605,
  1287,
  3,
  2707,
  2033,
  280,
  139,
  622],
 [222, 23, 193, 26, 1, 426],
 [1,
  140,
  2034,
  326,
  303,
  331,
  2708,
  2,
  1,
  6389,
  386,
  2,
  1,
  6390,
  6391,
  2,
  6392,
  3678,
  2,
  1,
  1226,
  6,
  64,
  747],
 [13, 2, 1, 1380, 16, 1, 1859, 2, 1, 1380, 5, 29, 1549, 2709],
 [25,
  24,
  2,
  327,
  11,
  14,
  13,
  108,
  4,
  52,
  1643,
  19,
  6,
  770,
  380,
  2,
  4558,
  6393,
  4559,
  5,
  1,
  55,
  433,
  519,
  1,
  8,
  119,
  110,
  15,
  251,
  6,
  3679],
 [2215,
  80,
  2,
  1,
  8,
  453,
  44,
  1,
  1644,
  1550,
  5,
  1,
  1645,
  189,
  2215,
  80,
  2,
  1,
  8,
  453,
  17,
  533,
  44,
  1,
  1644,
  1550,
  214,
  3117,
  881,
  399,
  19,
  100,
  1,
  1645,
  189,
  3680],
 [1084, 2035, 36, 1, 3681, 35, 12, 1, 8, 41, 312, 35],
 [151, 23, 7, 366, 1381, 1227, 32, 6, 97, 157, 3106, 434],
 [11,
  14,
  2,
  58,
  3,
  107,
  6,
  621,
  28,
  43,
  129,
  7,
  1456,
  414,
  6394,
  66,
  521,
  3682,
  1129,
  3,
  49,
  3683,
  2032,
  115,
  1288,
  1129,
  10,
  1036,
  212,
  8,
  1456,
  1179,
  6,
  454,
  2,
  4560,
  414,
  12,
  85,
  204,
  299,
  368,
  3,
  2710,
  159,
  27,
  269],
 [546, 298, 68, 1860, 247, 165, 350, 3, 636, 204, 6, 2417, 945],
 [1756,
  173,
  332,
  3118,
  6395,
  32,
  5,
  161,
  6396,
  3,
  161,
  2711,
  2,
  6397,
  1457,
  2,
  461],
 [82,
  25,
  13,
  16,
  576,
  124,
  5,
  1,
  1646,
  103,
  3,
  17,
  1,
  1037,
  2,
  1,
  1551,
  183,
  1646,
  3684,
  15,
  4,
  1130,
  637,
  1180,
  503,
  2,
  1,
  322,
  60,
  3,
  917,
  1001,
  3119,
  183,
  1646,
  3684,
  6398],
 [29,
  2712,
  2713,
  2,
  1,
  9,
  1002,
  2,
  4,
  858,
  2714,
  171,
  3,
  46,
  1131,
  212,
  6,
  1,
  1382,
  2,
  1,
  441,
  2,
  1038,
  1647,
  104,
  139,
  3685,
  6399,
  6400,
  2418,
  2686,
  101,
  6401,
  6402,
  6403,
  623,
  6404,
  101,
  6405,
  4561,
  101,
  6406,
  6407,
  6408,
  2419,
  452],
 [34,
  7,
  104,
  1,
  19,
  27,
  3686,
  54,
  6,
  4,
  882,
  317,
  5,
  1,
  4562,
  823,
  34,
  7,
  104,
  1,
  19,
  27,
  3686,
  54,
  6,
  4,
  882,
  317,
  5,
  1,
  4562,
  823],
 [4,
  90,
  230,
  25,
  48,
  51,
  13,
  1,
  131,
  1858,
  704,
  45,
  1,
  271,
  2,
  1,
  2216,
  3,
  2715,
  918,
  4563,
  674,
  2420,
  2,
  1,
  240,
  272,
  186,
  1861],
 [4564, 20, 4565, 2, 1, 1289, 788],
 [43, 82, 53, 48, 51, 56, 7, 4, 74, 6, 690, 250, 131, 202, 3, 97, 157, 748],
 [11, 7, 2421, 2422, 286, 1003, 6, 1, 418, 101],
 [1458, 3120, 83, 3687, 768, 6, 203, 85, 6409],
 [178,
  446,
  3688,
  946,
  3689,
  398,
  21,
  18,
  75,
  29,
  4566,
  3121,
  289,
  4,
  1862,
  1552,
  15,
  318,
  598,
  41,
  12,
  1459],
 [731, 1553, 3690, 1290, 47, 4567, 1863, 1383, 3691, 1282, 315, 458, 3122],
 [91, 46, 34, 2, 4, 261, 33, 241, 109, 26, 224],
 [1004,
  489,
  1034,
  3692,
  2217,
  3693,
  431,
  11,
  176,
  29,
  332,
  19,
  5,
  1,
  9,
  119,
  3,
  4,
  466,
  672,
  187],
 [48,
  51,
  125,
  13,
  7,
  1085,
  181,
  518,
  2,
  1,
  1384,
  35,
  10,
  76,
  15,
  29,
  454,
  36,
  1,
  236,
  35,
  789,
  3,
  518],
 [4,
  947,
  39,
  38,
  233,
  6,
  3123,
  972,
  2716,
  16,
  4,
  6410,
  277,
  17,
  1,
  9,
  3,
  8,
  3694,
  2423,
  351,
  6,
  57,
  2717,
  407,
  37,
  114,
  15,
  270,
  1385,
  2,
  1,
  536,
  189,
  1132],
 [585, 331, 128, 1864, 4, 6411, 2036, 19, 17, 1, 1865, 67, 2, 1, 547],
 [47,
  21,
  18,
  176,
  29,
  606,
  157,
  607,
  19,
  638,
  65,
  235,
  134,
  49,
  130,
  77,
  5,
  182,
  5,
  1,
  238,
  977],
 [726, 30, 1181, 7, 618, 537, 17, 1, 384, 2, 771, 3, 1228, 40, 305],
 [419,
  639,
  418,
  446,
  7,
  606,
  157,
  686,
  634,
  3,
  1182,
  2,
  339,
  1224,
  2,
  883,
  2,
  601,
  5,
  1,
  220,
  2,
  32,
  50],
 [633, 7, 1, 101, 2, 1460, 85, 12, 1039],
 [1125,
  20,
  23,
  1386,
  4,
  1291,
  79,
  273,
  5,
  1,
  167,
  285,
  2,
  1,
  9,
  790,
  10,
  1229,
  6412,
  2,
  405,
  656,
  264,
  112,
  1757],
 [25,
  48,
  51,
  56,
  2,
  92,
  50,
  128,
  4,
  19,
  357,
  50,
  6413,
  235,
  77,
  5,
  1,
  3695,
  1866,
  2,
  1,
  9,
  884,
  565,
  2718],
 [47,
  11,
  14,
  7,
  29,
  3124,
  97,
  157,
  675,
  19,
  5,
  1,
  705,
  1461,
  1,
  19,
  54,
  42,
  460,
  1758,
  3,
  27,
  4568,
  12,
  112,
  4,
  705,
  1183,
  1867,
  74,
  1868],
 [151, 24, 7, 87, 859, 1184, 3, 1545, 601, 1230, 262, 123, 3, 4569, 2211, 480],
 [11, 14, 7, 87, 245, 1003, 599, 5, 81, 3, 177],
 [3125, 676],
 [911, 2424, 316, 91, 446, 5, 249, 24],
 [151, 278, 24, 2, 33, 266, 3696, 6, 6414, 5, 2208],
 [11,
  4570,
  6,
  43,
  316,
  55,
  12,
  232,
  50,
  7,
  1,
  995,
  2,
  1,
  379,
  358,
  242,
  1554,
  89,
  1,
  479,
  1869,
  265,
  206,
  45,
  9,
  3697,
  10,
  3,
  699,
  3698,
  12,
  6415,
  103,
  206,
  45,
  2037,
  10],
 [46,
  23,
  2,
  6416,
  7,
  749,
  6417,
  1292,
  86,
  3,
  271,
  2,
  6418,
  3,
  6419,
  1133,
  1462,
  470,
  12,
  669],
 [47,
  21,
  18,
  70,
  316,
  4,
  3699,
  253,
  6420,
  132,
  750,
  306,
  1648,
  293,
  1134,
  673,
  1648],
 [732, 7, 6421, 159, 2, 1, 9, 1380],
 [106,
  1649,
  11,
  14,
  7,
  4,
  2719,
  358,
  881,
  6,
  1005,
  3,
  209,
  791,
  1293,
  3,
  332,
  101,
  10],
 [106, 30, 31, 7, 2720, 2, 198, 197],
 [11,
  14,
  2,
  1,
  260,
  33,
  5,
  232,
  49,
  44,
  6422,
  3,
  3700,
  2,
  1,
  145,
  159,
  548,
  4,
  255,
  772,
  1759],
 [1453, 6423, 90, 230, 23, 7, 123, 3, 6424, 338],
 [249, 6425, 2721, 4571, 26, 3126, 6426, 6427, 504],
 [48, 51, 56, 1650, 1231, 7, 1135, 2, 1, 9, 1231, 6, 28, 126],
 [25,
  11,
  13,
  2,
  1,
  66,
  107,
  4,
  97,
  773,
  191,
  74,
  15,
  59,
  5,
  1,
  2710,
  103,
  6,
  63,
  640,
  2,
  555,
  5,
  1040,
  6,
  1,
  55,
  67,
  2,
  1,
  824,
  10],
 [4,
  20,
  23,
  16,
  3701,
  1555,
  6,
  57,
  339,
  71,
  1232,
  3,
  140,
  194,
  373,
  5,
  6428,
  6429,
  6430],
 [6431, 31, 2, 290, 5, 2722, 7, 1233, 1387],
 [34, 26, 95, 109, 69, 53, 13],
 [3702,
  6432,
  142,
  1294,
  272,
  25,
  28,
  11,
  129,
  116,
  1,
  1294,
  4572,
  16,
  4,
  19,
  100,
  1,
  9,
  1294,
  272,
  3,
  1295,
  89,
  1,
  9,
  6433,
  102,
  608],
 [125,
  26,
  1746,
  2,
  1,
  2028,
  35,
  519,
  1,
  885,
  2,
  1,
  9,
  213,
  184,
  3,
  471,
  412,
  44,
  1,
  407,
  2,
  1,
  1296,
  733,
  4573,
  102,
  10,
  118,
  104,
  28,
  1556,
  15,
  162,
  2218,
  227,
  1,
  9,
  236,
  35,
  302,
  12,
  1,
  657,
  386,
  168,
  5,
  1,
  605,
  471,
  236,
  6434,
  577,
  2219,
  284,
  2,
  1,
  213,
  184,
  35,
  490,
  102,
  10,
  15,
  4,
  2708,
  2,
  1,
  2723,
  2425,
  292,
  2724,
  124,
  2,
  222,
  3,
  328,
  317,
  860,
  5,
  1,
  471,
  35,
  139,
  162,
  2038,
  12,
  112,
  104,
  349,
  83,
  423,
  201,
  5,
  92,
  2426,
  4574,
  1086,
  2038,
  2039,
  201,
  40,
  10,
  1449,
  491],
 [58,
  303,
  80,
  4,
  97,
  157,
  374,
  101,
  6435,
  146,
  17,
  1,
  6436,
  60,
  2,
  1,
  81,
  7,
  104,
  1,
  138,
  413,
  2,
  1,
  19,
  27,
  214],
 [1870, 11, 13, 2, 1, 2220, 3703, 6, 1, 2715, 918],
 [641,
  13,
  2,
  312,
  2725,
  5,
  46,
  24,
  7,
  2427,
  919,
  5,
  886,
  6,
  706,
  430,
  168,
  792,
  231],
 [6437, 1463, 3127],
 [2726, 292, 25, 28, 54, 11, 16, 624, 226, 468, 37],
 [34, 2, 1, 84, 7, 63, 19, 186, 173, 32],
 [11,
  14,
  2,
  1,
  58,
  6,
  28,
  1556,
  176,
  4,
  52,
  237,
  419,
  47,
  19,
  1234,
  1,
  209,
  642,
  5,
  1,
  260,
  14,
  4,
  1457,
  32,
  15,
  715,
  5,
  1,
  9,
  447,
  5,
  643,
  4575,
  2040,
  3699,
  1297,
  793,
  2428,
  6438,
  6,
  447,
  186,
  408,
  6439,
  3,
  447,
  6440],
 [6441, 14, 6, 6442, 32],
 [241,
  586,
  751,
  48,
  51,
  125,
  2429,
  16,
  57,
  6443,
  292,
  104,
  15,
  415,
  256,
  22,
  1,
  9,
  94],
 [6444,
  2727,
  6445,
  354,
  1185,
  6,
  235,
  6446,
  1041,
  491,
  677,
  221,
  146,
  89,
  1,
  281,
  733,
  26,
  281,
  3128,
  4576,
  6,
  6447,
  1041,
  491],
 [396,
  3129,
  26,
  4577,
  1087,
  108,
  29,
  505,
  2728,
  8,
  93,
  3,
  270,
  430,
  8,
  188,
  1135],
 [641,
  1760,
  602,
  2,
  4,
  330,
  1651,
  44,
  28,
  267,
  752,
  267,
  794,
  362,
  716,
  10,
  36,
  4,
  6448,
  1871,
  9,
  625,
  267,
  148,
  161,
  10,
  29,
  209,
  2221,
  15,
  59,
  6,
  4,
  914,
  5,
  231],
 [20,
  30,
  31,
  282,
  20,
  23,
  128,
  29,
  3704,
  79,
  733,
  6,
  29,
  2729,
  4578,
  2,
  79,
  1557,
  5,
  1,
  85,
  1761,
  658,
  1652,
  2,
  1,
  4579,
  385,
  37],
 [46,
  24,
  23,
  2,
  4,
  1006,
  104,
  1088,
  1872,
  6,
  706,
  425,
  118,
  1,
  609,
  64,
  420,
  3,
  1,
  391,
  3130,
  920,
  1,
  4580,
  2730,
  104,
  321,
  587,
  3705,
  1,
  64,
  420,
  3,
  4581,
  197,
  921,
  587,
  922],
 [30, 31, 2, 1, 9, 198, 7, 29, 1762, 2688, 78, 2, 9, 198],
 [6449, 54, 34, 14, 7, 566, 2, 1, 9, 447, 369, 1558, 109, 26, 4582, 4583],
 [3131,
  6450,
  232,
  16,
  3131,
  2,
  1,
  549,
  4584,
  6451,
  6452,
  4585,
  253,
  4586,
  3,
  6453,
  6454,
  6455,
  5,
  1,
  746,
  6456,
  2,
  1,
  6457,
  103,
  49,
  6458,
  6459,
  6460,
  6461,
  6462,
  6463,
  6464,
  6465,
  3,
  6466,
  6467,
  50,
  4587,
  2,
  1,
  4588,
  549,
  4584,
  6468,
  6469,
  2,
  49,
  235,
  139,
  6470,
  5,
  1,
  167,
  2,
  1,
  3131,
  2041,
  3,
  6471,
  83,
  6472,
  1284,
  17,
  6473],
 [25,
  345,
  54,
  82,
  53,
  180,
  128,
  4,
  52,
  214,
  19,
  6,
  2042,
  626,
  126,
  1042,
  45,
  366,
  280,
  27,
  852,
  5,
  1,
  147,
  216,
  2,
  1,
  9,
  322,
  60,
  62,
  923,
  124,
  6,
  1873,
  280,
  887,
  149,
  112,
  59,
  5,
  1,
  8,
  322,
  60],
 [1298, 44, 1874, 2, 297, 825, 223, 2043, 3, 179, 340],
 [4, 21, 18, 14, 7, 4, 19, 5, 1, 409],
 [20, 11, 1235, 4589, 3132, 71, 461, 8, 6474],
 [2044, 427, 2, 120, 141, 1036, 26, 729, 427],
 [1186, 418, 23, 2, 1, 33, 644, 3133, 1859, 2, 252, 8, 274, 1236],
 [30, 31, 7, 1079, 1187, 5, 1558, 978, 2, 4, 144, 295, 38, 4590],
 [2222, 47, 23, 23, 7, 1875, 5, 1, 61, 8, 506, 2, 1, 58],
 [34,
  14,
  7,
  1,
  1653,
  1763,
  200,
  4,
  1763,
  2,
  1,
  150,
  186,
  699,
  220,
  2,
  1,
  734,
  392,
  6,
  2223,
  461],
 [21,
  18,
  6,
  28,
  689,
  281,
  255,
  1,
  271,
  2,
  268,
  27,
  1388,
  17,
  1,
  9,
  60,
  2,
  1,
  81],
 [48,
  51,
  2,
  58,
  7,
  144,
  124,
  100,
  1,
  9,
  60,
  2,
  1,
  81,
  227,
  1,
  367,
  335,
  102,
  37],
 [507,
  1188,
  304,
  1876,
  11,
  13,
  2,
  33,
  1237,
  50,
  16,
  2430,
  304,
  5,
  1,
  96,
  2,
  1,
  8,
  1136,
  753,
  37],
 [1447, 23, 7, 1184, 2224, 1089, 3, 1238, 3134, 601],
 [3135, 472, 22, 826, 88, 6, 4591, 499, 4592, 13, 89, 1, 359],
 [178, 47, 30, 31, 26, 65, 498],
 [122,
  73,
  4593,
  32,
  6,
  4,
  1007,
  2,
  1,
  41,
  147,
  2731,
  3,
  29,
  209,
  62,
  1389,
  451,
  270,
  1043,
  3706,
  192,
  416,
  1,
  41,
  147,
  1299,
  10,
  22,
  29,
  25,
  1090,
  194,
  378],
 [84,
  11,
  244,
  130,
  498,
  26,

In [ ]:
word_index=tokenizer.word_index

In [ ]:
max_sequence_length=max(len(seq) for seq in train_sequences)
max_sequence_length

205

In [ ]:
train_padded=pad_sequences(train_sequences,maxlen=max_sequence_length,padding="post")
test_padded=pad_sequences(test_sequences,maxlen=max_sequence_length,padding="post")

In [ ]:
train_padded

array([[  21,   18,   14, ...,    0,    0,    0],
       [4527, 6341, 2200, ...,    0,    0,    0],
       [   1,   33,  321, ...,    0,    0,    0],
       ...,
       [ 354,  230,  418, ...,    0,    0,    0],
       [   4,   43,   24, ...,    0,    0,    0],
       [1334,   39,   38, ...,    0,    0,    0]], dtype=int32)

In [ ]:
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)

In [ ]:
train_labels

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [ ]:
import numpy as np
from gensim.models import Word2Vec
w2v_model=Word2Vec(sentences=[text.split() for text in train_texts],vector_size=100)

In [ ]:
embedding_dim=100
embedding_matrix=np.zeros((len(word_index)+1,embedding_dim))

In [ ]:
for word,i in word_index.items():
  if word in w2v_model.wv:
    embedding_matrix[i]=w2v_model.wv[word]

In [ ]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.56134892,  0.41877285,  0.03274717, ..., -0.51011091,
         0.03819739,  0.45008832],
       [-0.25035095,  0.39853352,  0.02397735, ..., -0.30027306,
        -0.23297808,  0.21549325],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
model=Sequential([
        Embedding(input_dim=len(word_index)+1,
                  output_dim=embedding_dim,
                  weights=[embedding_matrix],
        trainable=False),
        LSTM(128),
        Dense(2,activation="softmax")
])

In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 65s 323ms/step - accuracy: 0.5613 - loss: 0.6859 - val_accuracy: 0.5663 - val_loss: 0.6849
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 64s 320ms/step - accuracy: 0.5481 - loss: 0.6886 - val_accuracy: 0.5663 - val_loss: 0.6844
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 82s 319ms/step - accuracy: 0.5576 - loss: 0.6865 - val_accuracy: 0.5663 - val_loss: 0.6848
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 64s 318ms/step - accuracy: 0.5598 - loss: 0.6859 - val_accuracy: 0.5663 - val_loss: 0.6848
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 82s 317ms/step - accuracy: 0.5626 - loss: 0.6854 - val_accuracy: 0.5663 - val_loss: 0.6845
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 84s 326ms/step - accuracy: 0.5552 - loss: 0.6868 - val_accuracy: 0.5663 - val_loss: 0.6844
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 68s 340ms/step - accuracy: 0.5561 - loss: 0.6870 - val_accuracy: 0.5663 - val_loss: 0.6848
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 84s 352ms/step - accuracy: 0.5571 - loss: 0.6863 - val_accuracy: 0.5663 - val_loss: 0.6849
Epoch 9/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 82s 351ms/step - accuracy: 0.5518 - loss: 0.6876 - val_accuracy: 0.5663 - val_loss: 0.6847
Epoch 10/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 84s 359ms/step - accuracy: 0.5588 - loss: 0.6862 - val_accuracy: 0.5663 - val_loss: 0.6847

In [ ]:
test_loss,test_accuracy=model.evaluate(test_padded,test_labels)

63/63 ━━━━━━━━━━━━━━━━━━━━ 6s 98ms/step - accuracy: 0.5457 - loss: 0.6891

In [ ]:
test_accuracy

0.5490000247955322

In [ ]:
import random
import numpy as np
random_caption = train_texts.iloc[random.randint(0, len(train_texts)-1)]

random_sequence = tokenizer.texts_to_sequences([random_caption])
random_padded = pad_sequences(random_sequence, maxlen=max_sequence_length, padding='post')

prediction = model.predict(random_padded)

predicted_class = np.argmax(prediction)

print("Random Caption:", random_caption)
print("Predicted Class:", "Abnormal" if predicted_class == 0 else "Normal")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
Random Caption:  chest X-ray of case 4 showing right middle and lower lobe opacity
Predicted Class: Abnormal

GRU

In [ ]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

In [ ]:
df = df.sample(n=10000, random_state=42)

In [ ]:
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(df['Image Caption'])

In [ ]:
sequences = tokenizer.texts_to_sequences(df['Image Caption'])

In [ ]:
max_length = max(len(seq) for seq in sequences)

padded_sequences = pad_sequences(sequences, maxlen=max_length, padding="post")

In [ ]:
num_classes = 2
categorical_labels = to_categorical(df['label'], num_classes=num_classes)

In [ ]:
embedding_dim = 64

model = Sequential([

    Embedding(input_dim=1000, output_dim=embedding_dim),
    GRU(128, dropout=0.2),
    Dense(num_classes, activation="softmax")
])

In [ ]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

In [ ]:
model.fit(padded_sequences, categorical_labels, epochs=10)

Epoch 1/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 101s 314ms/step - accuracy: 0.5621 - loss: 0.6854
Epoch 2/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 142s 314ms/step - accuracy: 0.5652 - loss: 0.6852
Epoch 3/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 138s 302ms/step - accuracy: 0.5704 - loss: 0.6839
Epoch 4/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 93s 297ms/step - accuracy: 0.5637 - loss: 0.6853
Epoch 5/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 143s 299ms/step - accuracy: 0.5700 - loss: 0.6840
Epoch 6/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 148s 317ms/step - accuracy: 0.5661 - loss: 0.6850
Epoch 7/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 137s 300ms/step - accuracy: 0.5656 - loss: 0.6852
Epoch 8/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 142s 300ms/step - accuracy: 0.5680 - loss: 0.6841
Epoch 9/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 94s 299ms/step - accuracy: 0.5735 - loss: 0.6825
Epoch 10/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 142s 299ms/step - accuracy: 0.5723 - loss: 0.6830

In [ ]:
accuracy = model.evaluate(padded_sequences, categorical_labels, verbose=1)[1]
print(f"Accuracy: {accuracy * 100:.2f}%")

313/313 ━━━━━━━━━━━━━━━━━━━━ 21s 66ms/step - accuracy: 0.5673 - loss: 0.6840
Accuracy: 56.85%

In [ ]:
captions = df['Image Caption'].head(144).tolist()
data = '\n'.join([caption.strip() + '\\n' for caption in captions])

In [ ]:
print(data)

Computed tomography scan in axial view showing obliteration of the left maxillary sinus\n
Bacterial contamination occurred after completion of root canal treatment in the tooth, which remained with a temporary filling for 15 month.\n
The patient had residual paralysis of the hand after poliomyelitis. It was necessary to stabilize the thumb with reference to the index finger. This was accomplished by placing a graft from the bone bank between the first and second metacarpals. The roentgenogram shows the complete healing of the graft one year later.\n
Panoramic radiograph after immediate loading.\n
Plain abdomen x-ray: Multiple air levels at the mid-abdomen (arrows), no radiopaque shadow, and no air under the diaphragm.\n
A 3-year-old child with visual difficulties. Axial FLAIR image show a supra-sellar lesion extending to the temporal lobes along the optic tracts (arrows) with moderate mass effect, compatible with optic glioma. FLAIR hyperintensity is also noted in the left mesencephalon from additional tumoral involvement\n
Showing the subtrochanteric fracture in the porotic bone.\n
Post orthodontic treatment. Root canal therapy done with maxillary incisors\n
Two sequential thrombi in the distal segment of the obtuse marginal 2 (OM2).\n
An example of MRI image that takes advantage of joint effusion as contrast material in acute scenario. 57x46mm (150 x 150 DPI).\n
Child with abduction and flexion of right lower extremity and hyperextension of the tibia on the femur, associated with dislocation of the left hip, probably the result of the dangerous position of adduction in production of pathological dislocation. A roentgenogram of the mother’s pelvis, one week before delivery, showed this same deformity in utero.\n
Axial T2 HASTE MR image shows loss of normal trilaminar myometrial architecture and mild focal thinning of placenta at the site of compression of myometrium in front of aorta (black arrow), just proximal to the bifurcation. Normal trilaminar signal pattern of myometrium can be seen at other regions (white arrows)\n
Hydronephrosis appearance in sonography.\n
Coronary angiogram demonstrating occluded OM1 and OM2 arteries.\n
Cardiac catheterization showing normal coronaries and a tumor blush.\n
Follow-up coronary angiography and fluoroscopy showed a gap in the stent strut. A-D: a gap in the stent strut.\n
Right-sided metatarsal in dorsoplantar projection.Cow. Age group IV—cattle 4–8 years. (a) Narrow symphysis that is (b) indistinct from the bone surface.\n
Fourth patient’s MRI\n
Orthopantomograph\n
Focal steatosis of the liver parenchyma\n
Preoperative TTE, end diastole (preop pics).\n
Magnetic resonance T2 weighted image showing foraminal extensions of the cysts\n
Post-Treatment MRIAxial T1-weighted, contrast-enhanced image showing the same lesion as Figure 3.\n
Abdominal CT scan showing pancreatic pseudocyst\n
Axial contrast-enhanced computed tomography image of the abdomen 3 months after anti tuberculous treatment showing complete resolution of the lesions\n
Lytic lesions (arrows) involving the humerus.\n
Fluoroscopy image of EVAR procedure.\n
AP pelvis X-ray obtained 6 weeks from initial presentation which shows early femoral head collapse.\n
Postoperative control following periapical surgery.\n
CT image of the liver shows air in the hepatic veins (arrow) and air-contrast level in the inferior vena cava (arrowhead).\n
SFA perforated after Glidewire insertion in an attempt to cross the lesion.\n
Postoperative computed tomography scan\n
18-year-old woman with venous tumor thrombus. Axial T1W fat-saturated, postcontrast MR image of the pelvis.\n
X-ray control of calcaneus drilling\n
Transvaginal image of the maternal pelvis demonstrating cervical length. The probe is first advanced into the anterior fornix and then slightly withdrawn so that good image quality is maintained while avoiding placing pressure on the cervix. Cervical length is measured from internal to external os. The endocervical canal is also marked and can be differentiated by its echolucency. The anterior and posterior cervical walls are of similar thickness.\n
OPG showing a well defined corticated radiolucency containing two supernumerary premolars\n
Computed tomography scan obtained on December 24, 2014 (7 days before treatment).Notes: Scan demonstrates a mass in the upper lobe of the left lung, multiple enlarged lymph nodes in the mediastinum, and pleural effusion; arrow indicates abundant pericardial effusion around the pericardium.\n
Coronal contrast chest CT image showing the two aberrant arteries (white arrow) arising directly from the thoracic aorta and the left lower lobe cystic lesion.\n
Osteoid osteoma in the femur. Axial CT scan shows a nidus (arrow) within the cortex, with surrounding dense sclerosis (arrowhead)\n
Mandibular occlusal view radiograph showing fusion of mandibular teeth with talon cusp with respect to 41 and 42\n
Intraoperative T2w MR image showing the tumor and the first BBB target\n
Free air beneath the diaphragm at abdominal x-ray film\n
Posteroanterior radiography immediately before reintervention showing the inferior vena caval loop of the pacemaker lead strongly attached to the endothelium. The tip of the electrode is still attached the right ventricular wall. At that time an exit block was predominantly existent.\n
Après mise en place du drain thoracique\n
Venography of left innominate vein using catheter introduced via right common femoral vein. The site of perforation is well seen\n
CT spine showing a mass at level of C3 with marked osseous destruction.\n
Destroid lung due to progressive pulmonary tuberculosis in a 16-year-old boy. CT scan (lung window) shows diffuse bilateral small and large air-filled cystic lesions (black arrows) associated with ground-glass attenuation and disseminated miliary micronodular lesions on the right (white arrows).\n
View of giant cell tumor of thumb metacarpal preoperatively.\n
MRI showing high signals involving the superior sagittal sinus thrombosis on TW1.\n
Color Doppler echocardiography, parasternal modified short axis view. Middle LAD stenosis was incidentally found on rutine TTE. It was later confirmed by coronary angiography. See movie 13 [see Additional file 13]\n
Transverse view of lung using computed tomography. Leukemic infiltration is seen.\n
Calculation of mitral valve area(MVA) via planimetry method from parasternal short-axis view in one patient with mitral annulus calcification(MAC) after PTMC.\n
Catch of the muscles with 5.0 non-resorbable suture thread and their resection near the insertion; Eye prosthesis made up of a Polymethyl methacrylate) (PMMA) ball covered with a Polyethylene terephthalate shell (Dacron)\n
The AP view radiograph of the right hip demonstrates proximal migration of the lesser trochanter.\n
X-ray arthrogram showing mild contrast tracking along the proximal lateral aspect of the femoral component.\n
48 h reperfusion T2WI shows high-signal infarction smaller than lesion on DWI.\n
Computed tomography axial section after injection of contrast medium in parenchymal time showing a large thrombus in the left renal vein extending from the segmental renal veins to the inferior vena cava, complicated by cortical infarction.\n
Postoperative panoramic radiograph after surgery. The costochondral graft was adjusted to the left condyle area and secured on the left mandibular ramus by five bicortical screws for rigid internal fixation\n
Solid—cystic teratoma containing different types of tissue like fat, albuminous liquid and other solid parts (MRI, T1-gradient echo sequence, coronal).\n
Dental panoramic tomograph from 2016 showing extensive bone loss of the right mandible, left coronoid process and ramus.\n
Chest radiography shows a mass on the right lower mediastinum\n
Radiation-induced liver disease: a 21-year-old woman with lymphoma of the right anterior chest wall. The patient received 39.6 Gy to the right chest wall. CT obtained 5 weeks after the completion of radiation therapy shows a well-defined area of low attenuation in the liver with a sharp demarcation between the area of radiation and the normal liver. This is consistent with the straight-border sign of radiation change.\n
Underfilled root canal with void\n
Anterior-posterior radiograph of the left shoulder of a 36-year-old male patient showing the failed reconstruction of the acromioclavicular (AC) joint with an allograft because of type 5 AC separation\n
CT head with IV contrast with an arrow that indicates cerebral venous sinus thrombosis.\n
Pelvic X-RAY hours after the CT showed the gastric band and its connecting tube in the lower pelvis\n
Aneurysm of the descending thoracic aorta with a transverse diameter of 3,1 cm.\n
Contrast MRI head axial section showing an irregularly enhancing mass in the right medial temporal lobe anteriorly in the close proximity to the cavernous sinus and oculomotor nerve (arrow).\n
Endo-vaginal ultrasonography of anal sphincter in a patient with rectal prolapse: irregular and asymmetrical appearance of the internal anal sphincter (IAS arrow), without defect (A: anterior, and P: posterior).\n
Chest X-ray, which confirmed the position of guidewire, extending from the right internal jugular vein up to inferior vena cava\n
Sagittal CT angiogram of abdomen demonstrating mechanical fragmentation and displacement of stent.\n
Melorheostosis involving the ulnar aspect of the third proximal phalanx. Note that it takes on the appearance of dripping candle wax.\n
Barium swallow demonstrating the obstructive appearance of the GCT.\n
Pancreatic pseudoaneurysm (arrow) visualized in color Doppler examination – a result of the damage of pancreaticoduodenal artery, a complication of AP\n
MDCT angiography showing the location of CoA in a 1-month-old (B) girl (arrow).\n
Anterior uveitis with cystoid macular edema.In a 57-year-old female with quiescent anterior uveitis, peripheral vessel leakage and cystoid macular edema were detected.\n
Initial radiograph performed after the injury.\n
The high-frequency color Doppler ultrasonography manifestation of the apterium blood of the articulationes interphalangeae of digitus medius of the patients with bone erosion.\n
Image of the TMJ shows the morphology of the TMJ in an asymptomatic volunteer.\n
Axial view of PET-CT scan image demonstrates a large hypermetabolic mass with intense uptake of F18 Levo-DOPA in the posterior mediastinum near the left atrium which is consistent with paraganglioma.\n
Ocular ultrasound of the left eye demonstrating the dislocated lens in the vitreous cavity. Ocular ultrasound of the left eye at presentation demonstrating the dislocated lens (heterogeneous hyperechogenic oval-shaped mass) within the vitreous cavity (hypoechogenic).\n
Collateral circulation from the conus artery to the left anterior descending artery\n
Panoramic radiograph showing extensive radio-opaque lesion with well-defined corticated border.\n
CT scan of abdomen and pelvis with IV contrast coronal section showing perinephric hematoma, nonobtructive lower pole 6 mm stone and 1.1 cm obstructive proximal ureteral stone (arrow heads). Marked left perinephric stranding with extension of extracapsular hematoma to distal aorta, iliac vessels, and presacral space was noted.\n
Transthoracic echocardiography showed severely increased aortic root and ascending aorta with intimal flap.\n
Peripherally enhancing, irregular, marginated, subcentimeter lesion in segment IVa, and segment VII of liver‐ suspicious of metastasis.\n
T1 axial image shows hypointense lesions in the pontine region and at the periphery of the pons. Central pontine myelinolysis is a likely diagnosis, however, involvement of the temporal lobe and clinical features makes central pontine myelinolysis unlikely.\n
An inflated representation of the right hemisphere of a representative participant (medial and lateral views) marked with the locations of the regions of interest (ROIs) that were studied. CSv, cingulate sulcus visual area; PcM, precuneus; VIP, ventral intraparietal area; p2v, putative area 2v; PIVC, parietoinsular vestibular cortex.\n
MRI showing that the mass was greatly enhanced, with a clear portion in the nearby tissues.MRI showing that the mass was greatly enhanced, with a clear portion in the nearby tissues\n
A post-operative axial magnetic resonance image. The signal void caused by the presence of the steel and titanium implants obscures any details of the spinal cord or decompression.\n
Neonatal chest X‐ray of the larger fetus.\n
Coronal T1-weighted magnetic resonance imaging showing a tumor with homogenous low-signal intensity and well-defined margins.\n
CT showing gutta percha point communicating with the periapical area\n
Conventional design for hybrid prosthesis with long distal cantilevers.\n
Plain radiographs, though less sensitive than computed tomography, are an acceptable screening examination. A calcific focus is visible just anterior to C1.\n
Coupe axiale d’un scanner abdominal passant par le foie après injection du PC\n
Postoperative lateral MRI of a female patient, three months after surgery.\n
Multi-slice 16 row ECG- gated cardiac CT reveals an irregular mass in the right atrium and a moderate pericardial effusion.\n
Magnetic resonance angiography image showing almost complete thrombosis of the basilar artery (arrow). This is an extension from the vertebral artery dissection and thrombosis.\n
A 30-year-old-woman with genital tuberculosis. Hysterosalpingogram shows a beaded appearance at the right and left fallopian tubes associated with bilateral tubal occlusion (arrows). There is mild irregularity of the uterine cavity outline\n
Endoscopic ultrasonography revealed avascular a heteroechoic submucosal mass at the posterolateral wall of the duodenum.\n
Abdominal computed tomography reveals an ill-defined hypodense mass approximately 3.0 × 1.6 cm in diameter in the pancreatic tail.\n
Hand X-rays showing dense lines at the end of radius and ulna (white arrowheads).\n
Intra-oral periapical radiographs showing ill-defined radiolucency, displacement and resorption of apical parts of roots of teeth in the areas of lesion 2\n
OPG showing the area of osteolysis distal to 28\n
Posteroanterior chest radiograph depicts a solitary pulmonary nodule in the middle third of the right hemithorax (arrow). Slight spiculation of its contour can be appreciated.\n
Axial magnetic resonance imaging of case 2 revealed a mass measuring 2.0×2.0 cm in the retrobulbar compartment of the right orbit causing proptosis.\n
Abdominal CT scan showing an exophytic well-defined round mass in the duodenal bulb. The mass enhanced as gastric mucosa and was presumed to be a duodenal gastrointestinal stromal tumor (GIST).\n
Panoramic view showing multiple impacted permanent and supernumerary teeth, hypoplastic maxillary sinus and slender coronoid process.\n
CT scan showing multiple non-communicating cysts in liver and kidney\n
Sternal foramen.\n
Immediate ACL reconstruction postoperative radiographs in AP view.\n
Panoramic radiography view of patient before rehabilitation with prostheses in 2014.\n
CT fistulogram with coronal reconstruction (posterior to Figure 2) showing the bifurcation of the fistula tract; one opening into the external auditory canal (shown by right facing arrow) and other going to retroauricular region (shown by upward arrow).\n
Lateral radiograph of reticulum showing clearly demarcable diaphragmatic line and presence of potential and nonpotential metallic densities cranial to diaphragm.\n
Abdominal computed tomography (sagittal reconstruction): A: desmoid-type fibromatosis; B: sigmoid colon involved; C: ileal loop involved.\n
Orthopantomogram showing pinching space of the right TMJ\n
Preoperative emergency CT scan showing a cecal tract (oval) with stricture and adjacent hyperdense, elevated, and irregular area (arrow).\n
Preoperative x-ray, showing osteoarthritis of hip joint.\n
CT scan of the same patient in Figure 1, demonstrating loculation and septation of the pleural space, indicating a phase II empyema\n
Five-month’ post-operative radiograph showing sinus and onlay graft\n
AP “open mouth view” after removing “halo-vest” system.\n
Magnetic resonance imaging brachial plexus showing hypertrophy of the right plexus with contrast enhancement\n
Axial CT image of the lower pelvis. A well-circumscribed solid tumor is seen in the presacral region, with no signs of infiltration, in contact with the posterior wall of the rectum (arrow).\n
A chest radiograph shows reticulonodular shadowing with bilateral apical lung fibrosis and high density nodules in coal workers pneumoconiosis\n
TX-ray of knee in profile showing patellar agenesis\n
MRI after 5 months, T2-weighted image.\n
Supraglottic SCC – False cord. Axial contrast CT section through the false cords shows a mass within the right false cord and invading into the right PGS (black asterisk)\n
Angiography after catheterization of the innominate artery near the origin of the right common carotid and subclavian arteries demonstrating the occlusion of the brachiocephalic trunk (bold black arrow). Note that contrast media is not running along the right vertebral artery due to the retrograde blood flow in the vessel (subclavian-vertebral steal syndrome). Concomitant stenosis of the common carotid artery (thin black arrow) is a manifestation of the generalized atherosclerotic disease. Stenotic lesions of initial and mid-portion segments in the subclavian artery were not considered to be that significant for acute treatment. In case they progressed we considered endovascular treatment. White arrow: pacemaker wire.\n
Abdomen Doppler ultrasound. A well-defined hypoechoic area (~53×39 mm) at the quadrate lobe of the liver, showing that the internal echo of the mass was heterogeneous.\n
Micro-CT image of the rat tibias with the titanium implants.\n
Fluoroscopic image of descending aortogram in lateral view showing PDA device in situ with minimal residual flow across it\n
Biphalangeal fifth toe.\n
Nodal disease. Axial contrast-enhanced CT shows retroperitoneal lymph nodes (arrows).\n
MRI of the brain showing no mass or enhancing lesion.\n
CT scan of the abdomen with contrast media reveals a large-size intra-abdominal mass displacing the adjacent structures. In the same scan a suspicious lesion is identified in the right adrenal. In some rare cases desmoid tumors may co-exist with adrenal or thyroid carcinomas and adrenal adenomas.\n
CT-Scan with anastomotic lesion.\n
Three-dimensional (3D) magnetic resonance angiography (MRA) shows bilateral moyamoya disease that is more severe on the right side\n
Minilaparotomy-assisted transmesenteric pre-dilation with 0.018’ guide wire inserted 8 mm into the portal trunk after portal cavernoma recanalization with hydrophilic guide wire.\n
Echocardiogram 2 months after biventricular repair demonstrates an apex-forming left ventricle and mild residual left-ventricular hypertrophy\n
Fluoroscopic spot film of a tube cholangiogram demonstrating contrast (bile) extravasation (bile leak site; open arrow) from a dehisced isolated right intrahepatic bile duct segment (arrow). An adjacent biloma is seen with a drain in it.\n
Chest X-ray findings. Chest radiograph revealed an engorged pulmonary trunk with an abrupt cutoff of pulmonary vascularity in the distal portions bilaterally, indicative of the "Westermark sign" (arrows).\n
Lateral-view radiograph of a wrist that underwent arthrodesis with minimal fixation. Note the dorsal bone plate and the free carpometacarpal joints. The Kirschner wires that had been holding the bone plate and radiocarpal joint have been removed.\n
X-ray of the right hip showing an incomplete subtrochanteric fracture of right hip.\n

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])

In [ ]:
vocab_size=len(tokenizer.word_index)+1
vocab_size

1147

In [ ]:
sequences=[]

In [ ]:
for line in data.split("\n"):
  token_list=tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    ngram_sequence=token_list[:i+1]
    sequences.append(ngram_sequence)

In [ ]:
sequences

[[36, 37],
 [36, 37, 19],
 [36, 37, 19, 4],
 [36, 37, 19, 4, 22],
 [36, 37, 19, 4, 22, 24],
 [36, 37, 19, 4, 22, 24, 8],
 [36, 37, 19, 4, 22, 24, 8, 398],
 [36, 37, 19, 4, 22, 24, 8, 398, 3],
 [36, 37, 19, 4, 22, 24, 8, 398, 3, 1],
 [36, 37, 19, 4, 22, 24, 8, 398, 3, 1, 15],
 [36, 37, 19, 4, 22, 24, 8, 398, 3, 1, 15, 126],
 [36, 37, 19, 4, 22, 24, 8, 398, 3, 1, 15, 126, 57],
 [36, 37, 19, 4, 22, 24, 8, 398, 3, 1, 15, 126, 57, 2],
 [399, 400],
 [399, 400, 401],
 [399, 400, 401, 18],
 [399, 400, 401, 18, 199],
 [399, 400, 401, 18, 199, 3],
 [399, 400, 401, 18, 199, 3, 86],
 [399, 400, 401, 18, 199, 3, 86, 66],
 [399, 400, 401, 18, 199, 3, 86, 66, 48],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402, 87],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402, 87, 403],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402, 87, 403, 6],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402, 87, 403, 6, 7],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402, 87, 403, 6, 7, 404],
 [399, 400, 401, 18, 199, 3, 86, 66, 48, 4, 1, 402, 87, 403, 6, 7, 404, 405],
 [399,
  400,
  401,
  18,
  199,
  3,
  86,
  66,
  48,
  4,
  1,
  402,
  87,
  403,
  6,
  7,
  404,
  405,
  88],
 [399,
  400,
  401,
  18,
  199,
  3,
  86,
  66,
  48,
  4,
  1,
  402,
  87,
  403,
  6,
  7,
  404,
  405,
  88,
  406],
 [399,
  400,
  401,
  18,
  199,
  3,
  86,
  66,
  48,
  4,
  1,
  402,
  87,
  403,
  6,
  7,
  404,
  405,
  88,
  406,
  200],
 [399,
  400,
  401,
  18,
  199,
  3,
  86,
  66,
  48,
  4,
  1,
  402,
  87,
  403,
  6,
  7,
  404,
  405,
  88,
  406,
  200,
  2],
 [1, 42],
 [1, 42, 201],
 [1, 42, 201, 127],
 [1, 42, 201, 127, 407],
 [1, 42, 201, 127, 407, 3],
 [1, 42, 201, 127, 407, 3, 1],
 [1, 42, 201, 127, 407, 3, 1, 202],
 [1, 42, 201, 127, 407, 3, 1, 202, 18],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29, 409],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29, 409, 11],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29, 409, 11, 410],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29, 409, 11, 410, 1],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29, 409, 11, 410, 1, 203],
 [1, 42, 201, 127, 407, 3, 1, 202, 18, 408, 67, 29, 409, 11, 410, 1, 203, 6],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3,
  1],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3,
  1,
  90],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3,
  1,
  90,
  91],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3,
  1,
  90,
  91,
  44],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3,
  1,
  90,
  91,
  44,
  207],
 [1,
  42,
  201,
  127,
  407,
  3,
  1,
  202,
  18,
  408,
  67,
  29,
  409,
  11,
  410,
  1,
  203,
  6,
  411,
  11,
  1,
  412,
  413,
  89,
  29,
  414,
  43,
  204,
  7,
  90,
  25,
  1,
  49,
  415,
  205,
  1,
  128,
  5,
  416,
  417,
  1,
  206,
  20,
  1,
  129,
  418,
  3,
  1,
  90,
  91,
  44,
  207,
  2],
 [58, 26],
 [58, 26, 18],
 [58, 26, 18, 208],
 [58, 26, 18, 208, 419],
 [58, 26, 18, 208, 419, 2],
 [209, 50],
 [209, 50, 27],
 [209, 50, 27, 30],
 [209, 50, 27, 30, 92],
 [209, 50, 27, 30, 92, 59],
 [209, 50, 27, 30, 92, 59, 420],
 [209, 50, 27, 30, 92, 59, 420, 28],
 [209, 50, 27, 30, 92, 59, 420, 28, 1],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38, 93],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38, 93, 421],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38, 93, 421, 422],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38, 93, 421, 422, 5],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38, 93, 421, 422, 5, 93],
 [209, 50, 27, 30, 92, 59, 420, 28, 1, 210, 50, 38, 93, 421, 422, 5, 93, 59],
 [209,
  50,
  27,
  30,
  92,
  59,
  420,
  28,
  1,
  210,
  50,
  38,
  93,
  421,
  422,
  5,
  93,
  59,
  423],
 [209,
  50,
  27,
  30,
  92,
  59,
  420,
  28,
  1,
  210,
  50,
  38,
  93,
  421,
  422,
  5,
  93,
  59,
  423,
  1],
 [209,
  50,
  27,
  30,
  92,
  59,
  420,
  28,
  1,
  210,
  50,
  38,
  93,
  421,
  422,
  5,
  93,
  59,
  423,
  1,
  130],
 [209,
  50,
  27,
  30,
  92,
  59,
  420,
  28,
  1,
  210,
  50,
  38,
  93,
  421,
  422,
  5,
  93,
  59,
  423,
  1,
  130,
  2],
 [7, 68],
 [7, 68, 44],
 [7, 68, 44, 45],
 [7, 68, 44, 45, 211],
 [7, 68, 44, 45, 211, 6],
 [7, 68, 44, 45, 211, 6, 212],
 [7, 68, 44, 45, 211, 6, 212, 424],
 [7, 68, 44, 45, 211, 6, 212, 424, 22],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425, 7],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425, 7, 426],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425, 7, 426, 427],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425, 7, 426, 427, 31],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425, 7, 426, 427, 31, 131],
 [7, 68, 44, 45, 211, 6, 212, 424, 22, 213, 12, 425, 7, 426, 427, 31, 131, 11],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15,
  434],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15,
  434,
  25],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15,
  434,
  25,
  218],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15,
  434,
  25,
  218,
  435],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15,
  434,
  25,
  218,
  435,
  219],
 [7,
  68,
  44,
  45,
  211,
  6,
  212,
  424,
  22,
  213,
  12,
  425,
  7,
  426,
  427,
  31,
  131,
  11,
  1,
  132,
  428,
  133,
  1,
  214,
  429,
  38,
  6,
  215,
  16,
  430,
  431,
  6,
  214,
  432,
  213,
  433,
  14,
  216,
  217,
  4,
  1,
  15,
  434,
  25,
  218,
  435,
  219,
  2],
 [8, 1],
 [8, 1, 220],
 [8, 1, 220, 221],
 [8, 1, 220, 221, 4],
 [8, 1, 220, 221, 4, 1],
 [8, 1, 220, 221, 4, 1, 436],
 [8, 1, 220, 221, 4, 1, 436, 49],
 [8, 1, 220, 221, 4, 1, 436, 49, 2],
 [94, 437],
 [94, 437, 48],
 [94, 437, 48, 86],
 [94, 437, 48, 86, 66],
 [94, 437, 48, 86, 66, 222],
 [94, 437, 48, 86, 66, 222, 438],
 [94, 437, 48, 86, 66, 222, 438, 6],
 [94, 437, 48, 86, 66, 222, 438, 6, 126],
 [94, 437, 48, 86, 66, 222, 438, 6, 126, 439],
 [94, 437, 48, 86, 66, 222, 438, 6, 126, 439, 2],
 [134, 440],
 [134, 440, 441],
 [134, 440, 441, 4],
 [134, 440, 441, 4, 1],
 [134, 440, 441, 4, 1, 69],
 [134, 440, 441, 4, 1, 69, 95],
 [134, 440, 441, 4, 1, 69, 95, 3],
 [134, 440, 441, 4, 1, 69, 95, 3, 1],
 [134, 440, 441, 4, 1, 69, 95, 3, 1, 442],
 [134, 440, 441, 4, 1, 69, 95, 3, 1, 442, 443],
 [134, 440, 441, 4, 1, 69, 95, 3, 1, 442, 443, 70],
 [134, 440, 441, 4, 1, 69, 95, 3, 1, 442, 443, 70, 223],
 [134, 440, 441, 4, 1, 69, 95, 3, 1, 442, 443, 70, 223, 2],
 [17, 444],
 [17, 444, 3],
 [17, 444, 3, 34],
 [17, 444, 3, 34, 12],
 [17, 444, 3, 34, 12, 23],
 [17, 444, 3, 34, 12, 23, 224],
 [17, 444, 3, 34, 12, 23, 224, 445],
 [17, 444, 3, 34, 12, 23, 224, 445, 3],

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_sequence_len=max([len(seq) for seq in sequences])
sequences=pad_sequences(sequences,maxlen=max_sequence_len,padding="pre")
sequences

array([[  0,   0,   0, ...,   0,  36,  37],
       [  0,   0,   0, ...,  36,  37,  19],
       [  0,   0,   0, ...,  37,  19,   4],
       ...,
       [  0,   0,   0, ..., 221,   3,   9],
       [  0,   0,   0, ...,   3,   9,  71],
       [  0,   0,   0, ...,   9,  71,   2]], dtype=int32)

In [ ]:
from tensorflow.keras.utils import to_categorical
X=sequences[:,:-1]
y=sequences[:,-1]
y=to_categorical(y,num_classes=vocab_size)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

model=Sequential([
    Embedding(vocab_size,50),
    LSTM(100,return_sequences=False),
    Dense(vocab_size,activation="softmax")

])

In [ ]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 95ms/step - accuracy: 0.1437 - loss: 4.8944
Epoch 2/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 107ms/step - accuracy: 0.1585 - loss: 4.7487
Epoch 3/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 81ms/step - accuracy: 0.1575 - loss: 4.6835
Epoch 4/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.1641 - loss: 4.5438
Epoch 5/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 13s 110ms/step - accuracy: 0.1754 - loss: 4.4580
Epoch 6/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 91ms/step - accuracy: 0.1856 - loss: 4.4157
Epoch 7/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 91ms/step - accuracy: 0.1842 - loss: 4.2921
Epoch 8/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 107ms/step - accuracy: 0.2037 - loss: 4.1697
Epoch 9/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 83ms/step - accuracy: 0.2026 - loss: 4.1580
Epoch 10/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 106ms/step - accuracy: 0.2178 - loss: 4.0710
Epoch 11/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - accuracy: 0.2196 - loss: 3.9595
Epoch 12/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.2425 - loss: 3.8005
Epoch 13/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 105ms/step - accuracy: 0.2279 - loss: 3.8174
Epoch 14/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.2562 - loss: 3.6705
Epoch 15/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 94ms/step - accuracy: 0.2546 - loss: 3.5717
Epoch 16/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 106ms/step - accuracy: 0.2755 - loss: 3.4788
Epoch 17/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.2783 - loss: 3.3996
Epoch 18/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 100ms/step - accuracy: 0.3001 - loss: 3.2985
Epoch 19/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 102ms/step - accuracy: 0.3021 - loss: 3.2228
Epoch 20/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - accuracy: 0.3209 - loss: 3.1603
Epoch 21/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 104ms/step - accuracy: 0.3369 - loss: 3.0567
Epoch 22/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 81ms/step - accuracy: 0.3569 - loss: 2.9410
Epoch 23/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 79ms/step - accuracy: 0.3787 - loss: 2.8988
Epoch 24/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 100ms/step - accuracy: 0.3917 - loss: 2.7928
Epoch 25/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 97ms/step - accuracy: 0.4037 - loss: 2.7744
Epoch 26/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 89ms/step - accuracy: 0.4298 - loss: 2.6594
Epoch 27/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 104ms/step - accuracy: 0.4513 - loss: 2.6147
Epoch 28/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.4791 - loss: 2.5176
Epoch 29/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 79ms/step - accuracy: 0.5101 - loss: 2.4143
Epoch 30/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 103ms/step - accuracy: 0.5096 - loss: 2.3860
Epoch 31/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - accuracy: 0.5426 - loss: 2.2941
Epoch 32/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.5585 - loss: 2.2666
Epoch 33/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 97ms/step - accuracy: 0.5870 - loss: 2.1073
Epoch 34/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 114ms/step - accuracy: 0.5932 - loss: 2.1054
Epoch 35/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.6067 - loss: 2.0164
Epoch 36/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 100ms/step - accuracy: 0.6383 - loss: 1.9332
Epoch 37/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.6490 - loss: 1.8859
Epoch 38/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 103ms/step - accuracy: 0.6633 - loss: 1.8054
Epoch 39/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - accuracy: 0.6604 - loss: 1.7615
Epoch 40/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 102ms/step - accuracy: 0.6786 - loss: 1.7235
Epoch 41/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - accuracy: 0.6939 - loss: 1.6342
Epoch 42/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.7107 - loss: 1.5965
Epoch 43/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 103ms/step - accuracy: 0.7143 - loss: 1.5322
Epoch 44/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - accuracy: 0.7246 - loss: 1.4648
Epoch 45/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 90ms/step - accuracy: 0.7390 - loss: 1.4369
Epoch 46/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 105ms/step - accuracy: 0.7379 - loss: 1.4296
Epoch 47/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.7564 - loss: 1.3322
Epoch 48/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.7584 - loss: 1.3109
Epoch 49/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 105ms/step - accuracy: 0.7663 - loss: 1.2508
Epoch 50/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7894 - loss: 1.1825
Epoch 51/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 105ms/step - accuracy: 0.7884 - loss: 1.1549
Epoch 52/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 94ms/step - accuracy: 0.7753 - loss: 1.1402
Epoch 53/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 81ms/step - accuracy: 0.8103 - loss: 1.0422
Epoch 54/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 105ms/step - accuracy: 0.8041 - loss: 1.0607
Epoch 55/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8144 - loss: 1.0371
Epoch 56/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - accuracy: 0.8266 - loss: 0.9519
Epoch 57/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 102ms/step - accuracy: 0.8085 - loss: 0.9772
Epoch 58/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 95ms/step - accuracy: 0.8339 - loss: 0.8963
Epoch 59/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8442 - loss: 0.8565
Epoch 60/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 97ms/step - accuracy: 0.8526 - loss: 0.8375
Epoch 61/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 102ms/step - accuracy: 0.8569 - loss: 0.8166
Epoch 62/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8636 - loss: 0.7979
Epoch 63/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 104ms/step - accuracy: 0.8878 - loss: 0.7326
Epoch 64/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 83ms/step - accuracy: 0.8764 - loss: 0.7466
Epoch 65/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - accuracy: 0.8788 - loss: 0.7157
Epoch 66/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 105ms/step - accuracy: 0.8814 - loss: 0.7106
Epoch 67/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8897 - loss: 0.6732
Epoch 68/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 104ms/step - accuracy: 0.8836 - loss: 0.6613
Epoch 69/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.8986 - loss: 0.6180
Epoch 70/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 104ms/step - accuracy: 0.8976 - loss: 0.6198
Epoch 71/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - accuracy: 0.9012 - loss: 0.5951
Epoch 72/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 102ms/step - accuracy: 0.9063 - loss: 0.5716
Epoch 73/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.9058 - loss: 0.5449
Epoch 74/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 104ms/step - accuracy: 0.9152 - loss: 0.5512
Epoch 75/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 81ms/step - accuracy: 0.9195 - loss: 0.5094
Epoch 76/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 102ms/step - accuracy: 0.9246 - loss: 0.5042
Epoch 77/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - accuracy: 0.9207 - loss: 0.4907
Epoch 78/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.9213 - loss: 0.4898
Epoch 79/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 103ms/step - accuracy: 0.9288 - loss: 0.4444
Epoch 80/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9303 - loss: 0.4535
Epoch 81/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - accuracy: 0.9375 - loss: 0.4134
Epoch 82/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 98ms/step - accuracy: 0.9318 - loss: 0.4154
Epoch 83/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 104ms/step - accuracy: 0.9315 - loss: 0.4117
Epoch 84/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - accuracy: 0.9336 - loss: 0.4008
Epoch 85/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 103ms/step - accuracy: 0.9350 - loss: 0.3839
Epoch 86/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.9451 - loss: 0.3667
Epoch 87/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 11s 85ms/step - accuracy: 0.9476 - loss: 0.3581
Epoch 88/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 104ms/step - accuracy: 0.9461 - loss: 0.3484
Epoch 89/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9436 - loss: 0.3516
Epoch 90/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 93ms/step - accuracy: 0.9469 - loss: 0.3328
Epoch 91/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 102ms/step - accuracy: 0.9537 - loss: 0.3081
Epoch 92/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.9482 - loss: 0.3153
Epoch 93/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 104ms/step - accuracy: 0.9534 - loss: 0.2946
Epoch 94/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - accuracy: 0.9530 - loss: 0.2948
Epoch 95/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 104ms/step - accuracy: 0.9611 - loss: 0.2757
Epoch 96/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - accuracy: 0.9609 - loss: 0.2675
Epoch 97/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 10s 83ms/step - accuracy: 0.9642 - loss: 0.2586
Epoch 98/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 12s 98ms/step - accuracy: 0.9645 - loss: 0.2521
Epoch 99/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 97ms/step - accuracy: 0.9616 - loss: 0.2426
Epoch 100/100
92/92 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.9597 - loss: 0.2353

In [ ]:
import numpy as np
def generate_text(seed_text,next_words,max_sequence_len):
  for _ in range(next_words):
    token_list=tokenizer.texts_to_sequences([seed_text])[0]
    token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding="pre")
    predicted=np.argmax(model.predict(token_list,verbose=0),axis=-1)
    output_word=""
    for word,index in tokenizer.word_index.items():
      if index==predicted:
        output_word=word
        break
    seed_text+=" "+output_word
  return seed_text

In [ ]:
Actual_caption = "Panoramic radiograph after immediate loading."
seed_text="Panoramic radiograph after"
generate_text(seed_text,next_words=2,max_sequence_len=max_sequence_len)

'Panoramic radiograph after mild mild'

In [ ]:
Actual_caption = "Conventional design for hybrid prosthesis with long distal cantilevers."
seed_text="Conventional design for hybrid prosthesis with"
generate_text(seed_text,next_words=3,max_sequence_len=max_sequence_len)

'Conventional design for hybrid prosthesis with long distal cantilevers'

In [ ]:
Actual_Caption = "A computed tomography scan showing a mass in the gallbladder."
seed_text="A computed tomography scan showing "
generate_text(seed_text,next_words=5,max_sequence_len=max_sequence_len)